"use strict";
console.log(typeof 1);
console.log(typeof "a");
console.log(typeof true);
console.log(typeof {});
console.log(typeof Symbol());
console.log(typeof NaN);
console.log(typeof null);
console.log(typeof undefined);
